version: "3.9"

services:
  php-fpm:
    container_name: grant_admin_back
    build:
      context: ./../
      dockerfile: docker/php-fpm/Dockerfile
      args:
        - ENABLE_XDEBUG=${ENABLE_XDEBUG}
    ports:
      - ${PHP_FPM_PORT}:9000
    volumes:
      - ./../:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=GrantAdmin"
  nginx:
    container_name: grant_admin_nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ./../:/var/www
    depends_on:
      - php-fpm
  postgres:
    container_name: grant_admin_postgres
    build:
      context: ./postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data: