services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\Tests\Resources\Fixtures\:
        resource: '%kernel.project_dir%/tests/Resources/Fixtures/*'
        tags:
            - { "name": "doctrine.fixture.orm" }

    App\Shared\Infrastructure\Bus\CommandBus:
        public: true

    App\Shared\Infrastructure\Bus\QueryBus:
        public: true
